---
title: "Reproducibility: a LEGO Activity"
categories: [reproducibility, activity, beginner]
description: "Hands-on activity using LEGO builds to explore documentation practices and challenges related to reproducibility."
---

## Reproducibility activity using LEGO®

:::{.callout-learning}
After completing this session, you will be able to:

- Explain the importance of good documentation for reproducibility through the medium of LEGO®
- Identify challenges and good documentation practices to improve reproducibility
:::

::: callout-note
## Acknowledgments
This activity is largely based on the [LEGO® Metadata for Reproducibility game pack](http://eprints.gla.ac.uk/196477/), which was developed by [Mary Donaldson](https://orcid.org/0000-0002-1936-3499) and [Matt Mahon](https://orcid.org/0000-0001-8950-8422).

This work is licensed under the Creative Commons Attribution 4.0 International License. To view a 
copy of this license, visit http://creativecommons.org/licenses/by/4.0/.
:::

## Instructions

*  Gather into small groups
*  Get LEGO® blocks and (optional) open the template
    * Metadata template [.docx](resources/activity_reproducibility_lego/template_lego_activity_metadata.docx)

<details>
<summary><span style="background: yellow;">**Creation phase instructions**</span> (40 min)</summary>
1. Build a small house / building / structure of your choice using the provided 
LEGO blocks. Feel free to make this as complex and detailed as you would 
like and accessorize as desired. 
2. Keep notes on how to replicate the build, optionally using the template provided. 
3. Let an instructor know when you’re done and they will take a picture of 
the finished build. 
4. Disassemble build and prepare setup for the replication phase. 
</details>


***Hand off materials and metadata to another team (2 min)***

<details>
<summary><span style="background: #bbccff;">**Replication phase instructions**</span> (25 min)</summary>
1. Using the resources provided by the previous group, attempt to replicate 
their build.  
2. Consider which information was helpful and what additional information 
you would have found useful in attempting to replicate the previous build.  
3. Let an instructor know when you’re done and they will take a picture of 
the finished build. 
</details>

<span style="color: #88888888;">(instructor guide [here](resources/activity_reproducibility_lego/instructional_guide_reproducibility_activity.pdf))</span>

As you work, discuss the following questions within your small group.  At the end, we will share our thoughts and ideas with the larger group.

## Debrief Discussion

:::{.panel-tabset}
### Creation Phase

- Did you find this a simple way to document your process?
    - How would you document the process differently given more time or resources?
- Was there anything you found difficult to capture?
    - What information did you prioritize?
    - What did you choose to leave out?

### Replication Phase   

- What did you find straightforward to follow?
    - What questions would you have liked to ask the creators?
- Did you encounter any ambiguity in the instructions?
    - How would you have revised the instructions to make them clearer?

:::
