---
title: Git and GitHub Setup
categories: [git, github, setup, beginner]
description: "Git configuration settings and GitHub authentication via a Personal Access Token."
---

:::{.callout-learning}
After completing this session, you will be able to:

- Explain what the Terminal is and how it's relevant to Git setup tasks
- Describe why it's important to set a default merge strategy for Git
- Paraphrase why a <u>P</u>ersonal <u>A</u>ccess <u>T</u>oken (PAT) is necessary to interact with GitHub from your computer
:::

## Install Software First!

:::{.callout-important}
Before starting this lesson, make sure you have followed all the setup instructions on the [course home page](index.html)!
:::


## Set Git's Global Options

Before using Git, you need to tell it who you are, also known as setting the **global options**. You can do this either with command line code or with the R package `usethis`. For this lesson we will use the `usethis` package. However, you can also find the command line code to reference in the future.

::: {.callout-note}
## What's the Terminal?

Technically, the "Terminal" is an interface for the shell, a computer program. We use the Terminal to directly tell a computer what to do outside of R. This is different from the "Console" in your IDE (Positron, RStudio), which interprets R code and returns a value.

The Terminal should be visible by default in your IDE, but if it is not, you can open it by clicking **Terminal** {{< fa arrow-right >}} **New Terminal**

A Terminal tab should now be open right next to the Console tab.
:::

::: {.callout-tip}
## Don't Fear the Terminal!

Most of our Git operations will be done with R code, but there are some situations where you _must_ work in the Terminal and use command line. It may be daunting to code in the Terminal, but as your comfort increases over time, you might find you prefer it. Either way, it's beneficial to learn _enough_ command line and to not be intimidated in the Terminal. 

:::

### Configure GitHub Username and Email

To introduce ourselves to git we are going to update our global options with our GitHub user name and email information. We'll use the R code tab below but check out the terminal tab if doing this via command line is of interest.

::: {.callout-important}
## Case and Spelling Matter!

When you add your `user.email` to the global options you **must** use an address linked to your GitHub account, otherwise Git won't be able to sync to your account.

Your `user.name` is not used for matching Git to GitHub - it is just for helping other people identify you on the commits you write.  We recommend using your GitHub user name (e.g., `oharac`) but you can also use your human name (e.g, `Casey O'Hara`).
:::

::: {.panel-tabset}
#### Console {{< fa brands r-project >}}

**Step 1:** Tell Git (1) your GitHub username, (2) your GitHub-associated email address.

```r
usethis::use_git_config(user.name = "my_user_name", # <1>
                        user.email = "my_email@nceas.ucsb.edu") # <2>
```
1. Add your GitHub username (recommended) or human name.
2. Add your email address associated to you GitHub account.

**Step 2:** Define the default name for a branch that gets created when you make the first commit in a new Git repository (a.k.a. "repo").

```r
usethis::git_default_branch_configure(name = "main")
```

**Step 3:** Check to make sure everything looks correct.

```r
usethis::git_sitrep()
```

#### Terminal {{< fa terminal >}}

**Step 1:** Tell Git your GitHub username (recommended) or human name. Note that <u>if the code runs successfully, it will look like nothing happened</u>. We will check at the end to make sure it worked.

```bash
git config --global user.name "my_user_name"
```

**Step 2:** Tell Git your GitHub-associated email address.

```bash
git config --global user.email "my_email@nceas.ucsb.edu"
```

**Step 3:** Define the default name for a branch that gets created when you make the first commit in a new Git repository (a.k.a. "repo").

``` bash
git config --global init.defaultBranch main
```

**Step 4:** Check to make sure everything looks correct. The following command return the global options you have set.

``` bash
git config --global --list
```

:::

::: {.callout-note}
## Why Change the Default Branch Name?

Previously, the default branch name was "master" and this terminology for Git branches is problematic, which motivates us to update our default branch to "main" instead. 

:::

### Configure Strategy for Integrating Changes Across Branches

When you're working on the same GitHub repository as the rest of your team, what happens when you and a teammate edit the same file at the same time? How does Git 'know' how to reconcile those differences? Simply put, we tell Git how we want it to make that judgment call!

There are three options, "merge," "rebase," and "fast forward." **We recommend that you choose the "merge" strategy** as it will seamlessly handle easy situations where human oversight isn't needed but will flag more nuanced problems (called "merge conflicts") for you to resolve manually. For more information on "merge" versus "rebase", see [here](https://www.atlassian.com/git/tutorials/merging-vs-rebasing).  You can always revisit this decision later using essentially the same code below!

::: {.panel-tabset}
#### Console {{< fa brands r-project >}}

Set the default strategy for reconciling differences.

```r
usethis::use_git_config(pull.rebase = "false")
```

#### Terminal {{< fa terminal >}}

Set the default strategy for reconciling differences.

```bash
git config --global pull.rebase false
```

Note: The `--global` option will set this as default for all repositories on your computer.  If you forget this, it will only set for the current repo.
:::

<!-- It is important to highlight too that this configuration can be repository specific. This means you can configure how you want Git to reconcile two branches at a repository level instead of doing so for all repositories in which you work. This allows you to control how Git weaves things in when collaborating with others in a project-specific fashion. -->

<!-- If you don't define a merge strategy globally, you will have to define it for each repository that you create. If you have differences between branches and try to sync your local computer with the GitHub repository, you will likely get the following error message. Note that the error message itself gives you the terminal code that you'd need to fix it! -->

::: {.callout-warning}

#### Why did I get this error?

If you forget to set your `pull.rebase` option, you will get the following error message when you try to sync your local computer with GitHub.  Note, the error message gives you the terminal code to fix it!

```bash
hint: You have divergent branches and need to specify how to reconcile them.
hint: You can do so by running one of the following commands sometime before
hint: your next pull:
hint: 
hint:    git config pull.rebase false # merge (the default strategy) # <1>
hint:    git config pull.rebase true  # rebase
hint:    git config pull.ff only      # fast-forward only
hint: 
hint: You can replace "git config" with "git config --global" to set a default
hint: preference for all repositories. You can also pass --rebase, --norebase, 
hint: or --ff-only on the command line to override the configured default per
hint: invocation.
fatal: Need to specify how to reconcile divergent branches
```
1. This is the Terminal code to set the "merge" strategy, though we recommend you set this globally using the `--global` option.
:::

## Authenticate Your Computer with GitHub

While you will use your GitHub password to log in to your account on a web browser, in order to actually send code you write from your local computer up to GitHub, you'll need to "authenticate" in a different, more secure way.

The book [Happy Git and GitHub for the useR](https://happygitwithr.com/index.html) has a wealth of information related to working with Git in R, and the instructions below are based off of [Chapter 9: Personal access token for HTTPS](https://happygitwithr.com/https-pat.html) in that book.

We will be using a **Personal Access Token (PAT)** in this course. For better security and long term use, we recommend taking the extra steps to set up SSH keys (check out [Chapter 10 Set up Keys for SSH](https://happygitwithr.com/ssh-keys.html)).

::: {.callout-tip}
## Setting up Your PAT

1. Run `usethis::create_github_token()` in the Console.
2. A new browser window should open up to GitHub, showing all the "scopes" options. You can review the scopes, but you don't need to worry about which ones to select this time. The previous function automatically pre-selects some recommended scopes. **Go ahead and scroll to the bottom and click "Generate Token"**.
3. <u>Copy the generated token.</u> You will not be able to see this token again (ever) when you leave this page!
4. Back in the Console of your IDE, run `gitcreds::gitcreds_set()`.
5. Paste your PAT when the prompt asks for it.
6. Run `usethis::git_sitrep()` in the Console to check your Git configuration and that you've successful stored your PAT. 
**Note:** look for `Personal access token for 'https://github.com': '<discovered>'`

If you see `<unset>` instead of `<discovered>` means your PAT is not correctly set. You'll need to troubleshoot.

:::

Congrats! Now you've setup your authentication you should be able to work with GitHub in your IDE now.

